package domain

import "errors"

var (
	ErrUnauthenticated        = errors.New("authentication required")
	ErrForbidden              = errors.New("permission denied")
	ErrUnknownRole            = errors.New("unknown seller role")
	ErrUnknownPermission      = errors.New("unknown cms permission")
	ErrInvalidSellerScope     = errors.New("invalid seller scope")
	ErrInactiveStaff          = errors.New("seller staff is not active")
	ErrSellerStaffNotFound    = errors.New("seller staff not found")
	ErrStaffLookupFailed      = errors.New("seller staff lookup failed")
	ErrInvalidRoleConstraint  = errors.New("role constraint denied")
	ErrAuditRecorderRequired  = errors.New("audit recorder is required")
	ErrAuditWriteFailed       = errors.New("audit write failed")
	ErrInvalidAuthorizationIn = errors.New("invalid authorization input")

	ErrProductClientRequired      = errors.New("product client is required")
	ErrReviewRepositoryRequired   = errors.New("product moderation review repository is required")
	ErrProductNotFound            = errors.New("product not found")
	ErrProductServiceUnavailable  = errors.New("product service unavailable")
	ErrProductOwnershipMismatch   = errors.New("product does not belong to this seller")
	ErrInvalidProductTransition   = errors.New("invalid product status transition")
	ErrInvalidProductStatus       = errors.New("invalid product status")
	ErrInvalidModerationDecision  = errors.New("invalid moderation decision")
	ErrValidationFailed           = errors.New("validation failed")
	ErrReviewNotFound             = errors.New("product moderation review not found")
	ErrReviewAlreadyDecided       = errors.New("product moderation review already decided")
	ErrRejectionReasonRequired    = errors.New("rejection reason is required")
	ErrForceUnpublishReasonNeeded = errors.New("force unpublish reason is required")

	ErrCouponRepositoryRequired  = errors.New("coupon repository is required")
	ErrCouponNotFound            = errors.New("coupon not found")
	ErrCouponCodeAlreadyExists   = errors.New("coupon code already exists")
	ErrCouponOwnershipMismatch   = errors.New("coupon does not belong to this seller")
	ErrInvalidCouponStatus       = errors.New("invalid coupon status")
	ErrInvalidCouponDiscountType = errors.New("invalid coupon discount type")
	ErrInvalidCouponRule         = errors.New("invalid coupon rule")
	ErrCouponRedemptionNotFound  = errors.New("coupon redemption not found")
	ErrCouponRedemptionDuplicate = errors.New("coupon redemption already exists")
	ErrCouponRedemptionConflict  = errors.New("coupon redemption conflicts with existing order redemption")
	ErrCouponUsageLimitReached   = errors.New("coupon usage limit reached")
	ErrCouponPerUserLimitReached = errors.New("coupon per-user limit reached")
	ErrCouponCurrencyMismatch    = errors.New("coupon currency mismatch")

	ErrCampaignRepositoryRequired      = errors.New("campaign repository is required")
	ErrCampaignCouponReaderRequired    = errors.New("campaign coupon reader is required")
	ErrCampaignNotFound                = errors.New("campaign not found")
	ErrCampaignOwnershipMismatch       = errors.New("campaign does not belong to this seller")
	ErrInvalidCampaignStatus           = errors.New("invalid campaign status")
	ErrInvalidCampaignStatusTransition = errors.New("invalid campaign status transition")
	ErrCampaignCompletedReadOnly       = errors.New("completed campaign is read-only")
	ErrCampaignBudgetExhausted         = errors.New("campaign budget exhausted")
	ErrCampaignUsageLimitReached       = errors.New("campaign usage limit reached")
	ErrCampaignPerUserLimitReached     = errors.New("campaign per-user limit reached")
	ErrCampaignCouponNotLinked         = errors.New("coupon is not linked to campaign")
	ErrCampaignCurrencyMismatch        = errors.New("campaign currency mismatch")

	ErrAnalyticsRepositoryRequired = errors.New("seller analytics repository is required")
	ErrSellerContextRequired       = errors.New("seller context required")
	ErrInvalidAnalyticsDateRange   = errors.New("invalid analytics date range")
	ErrAnalyticsRangeTooLarge      = errors.New("analytics date range too large")
	ErrAnalyticsUnavailable        = errors.New("seller analytics temporarily unavailable")

	ErrSellerSettingsRepositoryRequired = errors.New("seller settings repository is required")
	ErrSellerSettingsNotFound           = errors.New("seller settings not found")

	ErrAuditLogRepositoryRequired = errors.New("audit log repository is required")
	ErrInvalidAuditLogFilter      = errors.New("invalid audit log filter")
	ErrAuditLogsUnavailable       = errors.New("audit logs temporarily unavailable")
)
