apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-local-config
  namespace: ecommerce-local
data:
  APP_ENV: local
  LOG_LEVEL: info
  REDIS_ADDR: redis:6379
  MONGO_HOST: mongodb
  MYSQL_HOST: mysql
  KAFKA_BROKERS: kafka:29092
  RABBITMQ_HOST: rabbitmq
  TYPESENSE_HOST: typesense
