INSERT INTO admin_permissions (permission_id, permission_key, description)
VALUES
  ('perm_admin_users_read', 'admin:users:read', 'View and list admin users'),
  ('perm_admin_users_write', 'admin:users:write', 'Create, update, disable, or re-enable admin users'),
  ('perm_users_read', 'users:read', 'Search and view platform users'),
  ('perm_users_status_update', 'users:status:update', 'Block or unblock platform users'),
  ('perm_sellers_read', 'sellers:read', 'Search sellers and view seller/KYC metadata'),
  ('perm_sellers_status_update', 'sellers:status:update', 'Approve, reject, or suspend sellers'),
  ('perm_orders_read', 'orders:read', 'Search orders and view dispute context'),
  ('perm_order_manual_review', 'orders:manual_review:write', 'Create or update order manual review decisions'),
  ('perm_payments_read', 'payments:read', 'Lookup payments and reconciliation metadata'),
  ('perm_refund_review', 'payments:refund:review', 'Approve or reject refund reviews'),
  ('perm_sessions_read', 'sessions:read', 'View admin session analytics'),
  ('perm_session_risk_read', 'sessions:risk:read', 'View suspicious session and risk data'),
  ('perm_catalog_moderation_read', 'catalog:moderation:read', 'View catalog moderation queues'),
  ('perm_catalog_moderation_write', 'catalog:moderation:write', 'Apply catalog moderation decisions'),
  ('perm_search_synonyms_read', 'search:synonyms:read', 'View search synonym settings'),
  ('perm_search_synonyms_write', 'search:synonyms:write', 'Update search synonym settings'),
  ('perm_platform_settings_read', 'platform:settings:read', 'View platform settings'),
  ('perm_platform_settings_write', 'platform:settings:write', 'Update platform settings'),
  ('perm_audit_logs_read', 'audit:logs:read', 'View admin audit logs'),
  ('perm_audit_logs_export', 'audit:logs:export', 'Export admin audit logs')
ON DUPLICATE KEY UPDATE
  description = VALUES(description);

INSERT INTO admin_role_permissions (role, permission_key)
VALUES
  ('superadmin', 'admin:users:read'),
  ('superadmin', 'admin:users:write'),
  ('superadmin', 'users:read'),
  ('superadmin', 'users:status:update'),
  ('superadmin', 'sellers:read'),
  ('superadmin', 'sellers:status:update'),
  ('superadmin', 'orders:read'),
  ('superadmin', 'orders:manual_review:write'),
  ('superadmin', 'payments:read'),
  ('superadmin', 'payments:refund:review'),
  ('superadmin', 'sessions:read'),
  ('superadmin', 'sessions:risk:read'),
  ('superadmin', 'catalog:moderation:read'),
  ('superadmin', 'catalog:moderation:write'),
  ('superadmin', 'search:synonyms:read'),
  ('superadmin', 'search:synonyms:write'),
  ('superadmin', 'platform:settings:read'),
  ('superadmin', 'platform:settings:write'),
  ('superadmin', 'audit:logs:read'),
  ('superadmin', 'audit:logs:export'),
  ('operations_admin', 'users:read'),
  ('operations_admin', 'users:status:update'),
  ('operations_admin', 'sellers:read'),
  ('operations_admin', 'sellers:status:update'),
  ('operations_admin', 'orders:read'),
  ('operations_admin', 'orders:manual_review:write'),
  ('operations_admin', 'sessions:read'),
  ('operations_admin', 'sessions:risk:read'),
  ('operations_admin', 'catalog:moderation:read'),
  ('finance_admin', 'payments:read'),
  ('finance_admin', 'payments:refund:review'),
  ('catalog_admin', 'sellers:read'),
  ('catalog_admin', 'sellers:status:update'),
  ('catalog_admin', 'catalog:moderation:read'),
  ('catalog_admin', 'catalog:moderation:write'),
  ('catalog_admin', 'search:synonyms:read'),
  ('catalog_admin', 'search:synonyms:write'),
  ('readonly_admin', 'users:read'),
  ('readonly_admin', 'sellers:read'),
  ('readonly_admin', 'orders:read'),
  ('readonly_admin', 'sessions:read'),
  ('readonly_admin', 'catalog:moderation:read'),
  ('readonly_admin', 'search:synonyms:read'),
  ('readonly_admin', 'audit:logs:read')
ON DUPLICATE KEY UPDATE
  role = VALUES(role);
