package domain

import "errors"

var (
	ErrUnauthenticated               = errors.New("authentication required")
	ErrForbidden                     = errors.New("operation is not permitted")
	ErrInvalidRequest                = errors.New("invalid request")
	ErrInvalidPageToken              = errors.New("invalid page token")
	ErrTrackingRequired              = errors.New("tracking number and carrier are required")
	ErrMultiSellerFulfillmentPending = errors.New("multi-seller fulfillment is not supported by the order-level operation")
	ErrTemporarilyUnavailable        = errors.New("order dependency temporarily unavailable")

	ErrUnknownOrderStatus           = errors.New("unknown order status")
	ErrOrderStatusUnchanged         = errors.New("order status is unchanged")
	ErrInvalidOrderStatusTransition = errors.New("invalid order status transition")
	ErrUnknownOrderStatusActorType  = errors.New("unknown order status actor type")

	ErrInvalidCheckoutCommand    = errors.New("invalid checkout command")
	ErrInvalidOrder              = errors.New("invalid order")
	ErrInvalidAddress            = errors.New("invalid shipping address")
	ErrInvalidCurrency           = errors.New("invalid currency")
	ErrCartNotFound              = errors.New("cart not found")
	ErrCartForbidden             = errors.New("cart does not belong to buyer")
	ErrCartEmpty                 = errors.New("cart is empty")
	ErrInvalidCartItem           = errors.New("invalid cart item")
	ErrInvalidQuantity           = errors.New("invalid item quantity")
	ErrDuplicateCartItem         = errors.New("duplicate cart item")
	ErrProductUnavailable        = errors.New("product is unavailable")
	ErrVariantUnavailable        = errors.New("variant is unavailable")
	ErrCurrencyMismatch          = errors.New("product currency does not match cart currency")
	ErrInvalidPrice              = errors.New("invalid product price")
	ErrMissingSeller             = errors.New("product seller is missing")
	ErrInvalidOrderTotal         = errors.New("invalid order total")
	ErrInventoryUnavailable      = errors.New("inventory is unavailable")
	ErrInvalidReservation        = errors.New("invalid inventory reservation")
	ErrOrderCreateFailed         = errors.New("order creation failed")
	ErrOrderCreateOutcomeUnknown = errors.New("order creation outcome needs resolution")
	ErrIdempotencyKeyRequired    = errors.New("idempotency key is required")
	ErrIdempotencyKeyInvalid     = errors.New("idempotency key is invalid")
	ErrIdempotencyConflict       = errors.New("idempotency key was used for different checkout input")
	ErrCheckoutInProgress        = errors.New("checkout is already processing")
	ErrCheckoutFailed            = errors.New("checkout previously failed")

	ErrOrderNotFound                  = errors.New("order not found")
	ErrOrderForbidden                 = errors.New("order does not belong to buyer")
	ErrOrderNotPayable                = errors.New("order is not payable")
	ErrInvalidOrderAmount             = errors.New("invalid order amount")
	ErrUnsupportedCurrency            = errors.New("unsupported payment currency")
	ErrInventoryReservationExpired    = errors.New("inventory reservation expired")
	ErrPaymentIntentCreationFailed    = errors.New("payment intent creation failed")
	ErrPaymentIntentPendingResolution = errors.New("payment intent outcome needs resolution")
	ErrInvalidPaymentIntentResponse   = errors.New("invalid payment intent response")
	ErrPaymentOrderMismatch           = errors.New("payment does not match order")
	ErrPaymentAmountMismatch          = errors.New("payment amount or currency does not match order")
	ErrInvalidPaymentResult           = errors.New("invalid payment result")
	ErrUnsupportedPaymentResult       = errors.New("unsupported payment result")
	ErrInvalidPaymentTransition       = errors.New("invalid payment order transition")
	ErrInventoryFinalizationFailed    = errors.New("inventory finalization failed")
)
