apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: core
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: ecommerce-platform
type: Opaque
stringData:
  PAYMENT_MYSQL_DSN: payment_user:change-me@tcp(mysql.data.svc.cluster.local:3306)/payment_db?parseTime=true&multiStatements=true
  PAYMENT_INTERNAL_API_TOKEN: change-me-at-least-32-characters
  PAYMENT_EVENTS_AUTH_TOKEN: change-me-at-least-32-characters
  STRIPE_LIKE_PUBLIC_KEY: change-me
  STRIPE_LIKE_SECRET_KEY: change-me
  STRIPE_LIKE_WEBHOOK_SECRET: change-me
  STRIPE_LIKE_BASE_URL: ""
  STRIPE_LIKE_TIMEOUT: 5s
  RAZORPAY_LIKE_PUBLIC_KEY: change-me
  RAZORPAY_LIKE_SECRET_KEY: change-me
  RAZORPAY_LIKE_WEBHOOK_SECRET: change-me
  RAZORPAY_LIKE_BASE_URL: ""
  RAZORPAY_LIKE_TIMEOUT: 5s
