apiVersion: v1
kind: Secret
metadata:
  name: cms-service-secret
  namespace: core
  labels:
    app.kubernetes.io/name: cms-service
    app.kubernetes.io/part-of: ecommerce-platform
type: Opaque
stringData:
  CMS_MYSQL_DSN: cms_user:change-me@tcp(mysql.data.svc.cluster.local:3306)/cms_db?parseTime=true&multiStatements=true
  CMS_DB_PASSWORD: change-me
  CMS_INTERNAL_AUTH_TOKEN: ""
  CMS_PRODUCT_SERVICE_AUTH_TOKEN: change-me-at-least-32-characters
