apiVersion: v1
kind: Secret
metadata:
  name: search-service-secret
  namespace: core
  labels:
    app.kubernetes.io/name: search-service
    app.kubernetes.io/part-of: ecommerce-platform
    app.kubernetes.io/component: backend-service
type: Opaque
stringData:
  TYPESENSE_API_KEY: "change-me"
  RABBITMQ_URL: "amqp://change-me:change-me@rabbitmq.data.svc.cluster.local:5672/ecommerce"
  SEARCH_REDIS_PASSWORD: "change-me"
  PRODUCT_SERVICE_TOKEN: "change-me"
