apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: core
  labels:
    app.kubernetes.io/name: search-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  selector:
    app.kubernetes.io/name: search-service
  ports:
    - name: http
      port: 8085
      targetPort: http
    - name: grpc
      port: 9085
      targetPort: grpc
