apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-service-config
  namespace: core
  labels:
    app.kubernetes.io/name: recommendation-service
    app.kubernetes.io/part-of: ecommerce-platform
data:
  SERVICE_NAME: recommendation-service
  APP_ENV: dev
  RECOMMENDATION_LOG_LEVEL: info
  RECOMMENDATION_HTTP_ADDR: :8088
  RECOMMENDATION_GRPC_ADDR: :9088
  RECOMMENDATION_GRPC_DEFAULT_DEADLINE: 500ms
  RECOMMENDATION_DEFAULT_LIMIT: "12"
  RECOMMENDATION_MAX_LIMIT: "100"
  RECOMMENDATION_MAX_IDENTIFIER_LENGTH: "128"
  RECOMMENDATION_MONGO_DATABASE: recommendation_db
  RECOMMENDATION_MONGO_ENSURE_INDEXES: "false"
  RECOMMENDATION_REDIS_ADDR: redis.data.svc.cluster.local:6379
  RECOMMENDATION_REDIS_DB: "3"
  RECOMMENDATION_CACHE_KEY_PREFIX: reco:v1
  RECOMMENDATION_CACHE_TTL_SECONDS: "900"
  RECOMMENDATION_PERSONALIZED_CACHE_TTL_SECONDS: "300"
  RECOMMENDATION_GUEST_CACHE_TTL_SECONDS: "300"
  RECOMMENDATION_STORAGE_FAIL_FAST: "true"
  RECOMMENDATION_EVENTS_ENABLED: "true"
  QUEUE_PROVIDER: kafka
  KAFKA_BROKERS: kafka.data.svc.cluster.local:9092
  RECOMMENDATION_EVENTS_TOPIC: recommendation.events
  RECOMMENDATION_EVENTS_RETRY_TOPIC: recommendation.events.retry
  RECOMMENDATION_EVENTS_DLQ_TOPIC: recommendation.events.dlq
  RECOMMENDATION_EVENTS_GROUP: recommendation-service-v1
  RECOMMENDATION_FEATURES_ENABLED: "true"
  RECOMMENDATION_RANKING_ENABLED: "true"
  RECOMMENDATION_RANKING_REBUILD_INTERVAL: 15m
  RECOMMENDATION_PERSONALIZATION_ENABLED: "true"
  RECOMMENDATION_AB_TESTING_ENABLED: "false"
  RECOMMENDATION_AB_FAIL_OPEN: "true"
