apiVersion: v1
kind: Secret
metadata:
  name: recommendation-service-secret
  namespace: core
  labels:
    app.kubernetes.io/name: recommendation-service
    app.kubernetes.io/part-of: ecommerce-platform
type: Opaque
stringData:
  RECOMMENDATION_MONGO_URI: mongodb://recommendation_user:change-me@mongodb.data.svc.cluster.local:27017/recommendation_db?authSource=recommendation_db
  RECOMMENDATION_REDIS_PASSWORD: change-me
  RECOMMENDATION_AB_DEFAULT_SALT: change-me
