apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: core
  labels:
    app.kubernetes.io/name: recommendation-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: recommendation-service
  ports:
    - { name: http, port: 8088, targetPort: http, protocol: TCP }
    - { name: grpc, port: 9088, targetPort: grpc, protocol: TCP }
