apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: core
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: ecommerce-platform
type: Opaque
stringData:
  NOTIFICATION_MONGO_URI: mongodb://notification_user:change-me@mongodb.data.svc.cluster.local:27017/notification_db?replicaSet=rs0
  NOTIFICATION_RABBITMQ_URL: amqp://change-me:change-me@rabbitmq.data.svc.cluster.local:5672/ecommerce
  NOTIFICATION_DELIVERY_ENCRYPTION_KEY: bG9jYWxfbm90aWZpY2F0aW9uX2tleV8zMmJ5dGVzISE=
  NOTIFICATION_EMAIL_SMTP_USERNAME: change-me
  NOTIFICATION_EMAIL_SMTP_PASSWORD: change-me
