// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ecommerce/recommendation/v1/recommendation.proto

package recommendationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendationType int32

const (
	RecommendationType_RECOMMENDATION_TYPE_UNSPECIFIED                RecommendationType = 0
	RecommendationType_RECOMMENDATION_TYPE_SIMILAR_PRODUCTS           RecommendationType = 1
	RecommendationType_RECOMMENDATION_TYPE_TRENDING                   RecommendationType = 2
	RecommendationType_RECOMMENDATION_TYPE_PERSONALIZED               RecommendationType = 3
	RecommendationType_RECOMMENDATION_TYPE_FREQUENTLY_BOUGHT_TOGETHER RecommendationType = 4
)

// Enum value maps for RecommendationType.
var (
	RecommendationType_name = map[int32]string{
		0: "RECOMMENDATION_TYPE_UNSPECIFIED",
		1: "RECOMMENDATION_TYPE_SIMILAR_PRODUCTS",
		2: "RECOMMENDATION_TYPE_TRENDING",
		3: "RECOMMENDATION_TYPE_PERSONALIZED",
		4: "RECOMMENDATION_TYPE_FREQUENTLY_BOUGHT_TOGETHER",
	}
	RecommendationType_value = map[string]int32{
		"RECOMMENDATION_TYPE_UNSPECIFIED":                0,
		"RECOMMENDATION_TYPE_SIMILAR_PRODUCTS":           1,
		"RECOMMENDATION_TYPE_TRENDING":                   2,
		"RECOMMENDATION_TYPE_PERSONALIZED":               3,
		"RECOMMENDATION_TYPE_FREQUENTLY_BOUGHT_TOGETHER": 4,
	}
)

func (x RecommendationType) Enum() *RecommendationType {
	p := new(RecommendationType)
	*p = x
	return p
}

func (x RecommendationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecommendationType) Descriptor() protoreflect.EnumDescriptor {
	return file_ecommerce_recommendation_v1_recommendation_proto_enumTypes[0].Descriptor()
}

func (RecommendationType) Type() protoreflect.EnumType {
	return &file_ecommerce_recommendation_v1_recommendation_proto_enumTypes[0]
}

func (x RecommendationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecommendationType.Descriptor instead.
func (RecommendationType) EnumDescriptor() ([]byte, []int) {
	return file_ecommerce_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{0}
}

type RecommendationContext int32

const (
	RecommendationContext_RECOMMENDATION_CONTEXT_UNSPECIFIED      RecommendationContext = 0
	RecommendationContext_RECOMMENDATION_CONTEXT_HOME_FEED        RecommendationContext = 1
	RecommendationContext_RECOMMENDATION_CONTEXT_PRODUCT_DETAIL   RecommendationContext = 2
	RecommendationContext_RECOMMENDATION_CONTEXT_CATEGORY_LISTING RecommendationContext = 3
	RecommendationContext_RECOMMENDATION_CONTEXT_CART             RecommendationContext = 4
	RecommendationContext_RECOMMENDATION_CONTEXT_CHECKOUT         RecommendationContext = 5
	RecommendationContext_RECOMMENDATION_CONTEXT_SEARCH_RESULTS   RecommendationContext = 6
	RecommendationContext_RECOMMENDATION_CONTEXT_SELLER_STORE     RecommendationContext = 7
)

// Enum value maps for RecommendationContext.
var (
	RecommendationContext_name = map[int32]string{
		0: "RECOMMENDATION_CONTEXT_UNSPECIFIED",
		1: "RECOMMENDATION_CONTEXT_HOME_FEED",
		2: "RECOMMENDATION_CONTEXT_PRODUCT_DETAIL",
		3: "RECOMMENDATION_CONTEXT_CATEGORY_LISTING",
		4: "RECOMMENDATION_CONTEXT_CART",
		5: "RECOMMENDATION_CONTEXT_CHECKOUT",
		6: "RECOMMENDATION_CONTEXT_SEARCH_RESULTS",
		7: "RECOMMENDATION_CONTEXT_SELLER_STORE",
	}
	RecommendationContext_value = map[string]int32{
		"RECOMMENDATION_CONTEXT_UNSPECIFIED":      0,
		"RECOMMENDATION_CONTEXT_HOME_FEED":        1,
		"RECOMMENDATION_CONTEXT_PRODUCT_DETAIL":   2,
		"RECOMMENDATION_CONTEXT_CATEGORY_LISTING": 3,
		"RECOMMENDATION_CONTEXT_CART":             4,
		"RECOMMENDATION_CONTEXT_CHECKOUT":         5,
		"RECOMMENDATION_CONTEXT_SEARCH_RESULTS":   6,
		"RECOMMENDATION_CONTEXT_SELLER_STORE":     7,
	}
)

func (x RecommendationContext) Enum() *RecommendationContext {
	p := new(RecommendationContext)
	*p = x
	return p
}

func (x RecommendationContext) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecommendationContext) Descriptor() protoreflect.EnumDescriptor {
	return file_ecommerce_recommendation_v1_recommendation_proto_enumTypes[1].Descriptor()
}

func (RecommendationContext) Type() protoreflect.EnumType {
	return &file_ecommerce_recommendation_v1_recommendation_proto_enumTypes[1]
}

func (x RecommendationContext) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecommendationContext.Descriptor instead.
func (RecommendationContext) EnumDescriptor() ([]byte, []int) {
	return file_ecommerce_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{1}
}

type GetRecommendationsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Context        RecommendationContext  `protobuf:"varint,2,opt,name=context,proto3,enum=ecommerce.recommendation.v1.RecommendationContext" json:"context,omitempty"`
	AnonymousId    string                 `protobuf:"bytes,3,opt,name=anonymous_id,json=anonymousId,proto3" json:"anonymous_id,omitempty"`
	ProductId      string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CategoryId     string                 `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	SellerId       string                 `protobuf:"bytes,6,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	CartProductIds []string               `protobuf:"bytes,7,rep,name=cart_product_ids,json=cartProductIds,proto3" json:"cart_product_ids,omitempty"`
	Limit          int32                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	Type           RecommendationType     `protobuf:"varint,9,opt,name=type,proto3,enum=ecommerce.recommendation.v1.RecommendationType" json:"type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_ecommerce_recommendation_v1_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_recommendation_v1_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *GetRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetContext() RecommendationContext {
	if x != nil {
		return x.Context
	}
	return RecommendationContext_RECOMMENDATION_CONTEXT_UNSPECIFIED
}

func (x *GetRecommendationsRequest) GetAnonymousId() string {
	if x != nil {
		return x.AnonymousId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetCartProductIds() []string {
	if x != nil {
		return x.CartProductIds
	}
	return nil
}

func (x *GetRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRecommendationsRequest) GetType() RecommendationType {
	if x != nil {
		return x.Type
	}
	return RecommendationType_RECOMMENDATION_TYPE_UNSPECIFIED
}

type RecommendationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationItem) Reset() {
	*x = RecommendationItem{}
	mi := &file_ecommerce_recommendation_v1_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationItem) ProtoMessage() {}

func (x *RecommendationItem) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_recommendation_v1_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationItem.ProtoReflect.Descriptor instead.
func (*RecommendationItem) Descriptor() ([]byte, []int) {
	return file_ecommerce_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendationItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *RecommendationItem) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RecommendationItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecommendationItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetRecommendationsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecommendationId string                 `protobuf:"bytes,1,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"`
	Type             RecommendationType     `protobuf:"varint,2,opt,name=type,proto3,enum=ecommerce.recommendation.v1.RecommendationType" json:"type,omitempty"`
	StrategyId       string                 `protobuf:"bytes,3,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Items            []*RecommendationItem  `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	GeneratedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	CacheTtlSeconds  int64                  `protobuf:"varint,6,opt,name=cache_ttl_seconds,json=cacheTtlSeconds,proto3" json:"cache_ttl_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_ecommerce_recommendation_v1_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_recommendation_v1_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecommendationsResponse) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *GetRecommendationsResponse) GetType() RecommendationType {
	if x != nil {
		return x.Type
	}
	return RecommendationType_RECOMMENDATION_TYPE_UNSPECIFIED
}

func (x *GetRecommendationsResponse) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *GetRecommendationsResponse) GetItems() []*RecommendationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetRecommendationsResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *GetRecommendationsResponse) GetCacheTtlSeconds() int64 {
	if x != nil {
		return x.CacheTtlSeconds
	}
	return 0
}

var File_ecommerce_recommendation_v1_recommendation_proto protoreflect.FileDescriptor

const file_ecommerce_recommendation_v1_recommendation_proto_rawDesc = "" +
	"\n" +
	"0ecommerce/recommendation/v1/recommendation.proto\x12\x1becommerce.recommendation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x03\n" +
	"\x19GetRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12L\n" +
	"\acontext\x18\x02 \x01(\x0e22.ecommerce.recommendation.v1.RecommendationContextR\acontext\x12!\n" +
	"\fanonymous_id\x18\x03 \x01(\tR\vanonymousId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\tR\n" +
	"categoryId\x12\x1b\n" +
	"\tseller_id\x18\x06 \x01(\tR\bsellerId\x12(\n" +
	"\x10cart_product_ids\x18\a \x03(\tR\x0ecartProductIds\x12\x14\n" +
	"\x05limit\x18\b \x01(\x05R\x05limit\x12C\n" +
	"\x04type\x18\t \x01(\x0e2/.ecommerce.recommendation.v1.RecommendationTypeR\x04type\"u\n" +
	"\x12RecommendationItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xe1\x02\n" +
	"\x1aGetRecommendationsResponse\x12+\n" +
	"\x11recommendation_id\x18\x01 \x01(\tR\x10recommendationId\x12C\n" +
	"\x04type\x18\x02 \x01(\x0e2/.ecommerce.recommendation.v1.RecommendationTypeR\x04type\x12\x1f\n" +
	"\vstrategy_id\x18\x03 \x01(\tR\n" +
	"strategyId\x12E\n" +
	"\x05items\x18\x04 \x03(\v2/.ecommerce.recommendation.v1.RecommendationItemR\x05items\x12=\n" +
	"\fgenerated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12*\n" +
	"\x11cache_ttl_seconds\x18\x06 \x01(\x03R\x0fcacheTtlSeconds*\xdf\x01\n" +
	"\x12RecommendationType\x12#\n" +
	"\x1fRECOMMENDATION_TYPE_UNSPECIFIED\x10\x00\x12(\n" +
	"$RECOMMENDATION_TYPE_SIMILAR_PRODUCTS\x10\x01\x12 \n" +
	"\x1cRECOMMENDATION_TYPE_TRENDING\x10\x02\x12$\n" +
	" RECOMMENDATION_TYPE_PERSONALIZED\x10\x03\x122\n" +
	".RECOMMENDATION_TYPE_FREQUENTLY_BOUGHT_TOGETHER\x10\x04*\xd7\x02\n" +
	"\x15RecommendationContext\x12&\n" +
	"\"RECOMMENDATION_CONTEXT_UNSPECIFIED\x10\x00\x12$\n" +
	" RECOMMENDATION_CONTEXT_HOME_FEED\x10\x01\x12)\n" +
	"%RECOMMENDATION_CONTEXT_PRODUCT_DETAIL\x10\x02\x12+\n" +
	"'RECOMMENDATION_CONTEXT_CATEGORY_LISTING\x10\x03\x12\x1f\n" +
	"\x1bRECOMMENDATION_CONTEXT_CART\x10\x04\x12#\n" +
	"\x1fRECOMMENDATION_CONTEXT_CHECKOUT\x10\x05\x12)\n" +
	"%RECOMMENDATION_CONTEXT_SEARCH_RESULTS\x10\x06\x12'\n" +
	"#RECOMMENDATION_CONTEXT_SELLER_STORE\x10\a2\x9f\x01\n" +
	"\x15RecommendationService\x12\x85\x01\n" +
	"\x12GetRecommendations\x126.ecommerce.recommendation.v1.GetRecommendationsRequest\x1a7.ecommerce.recommendation.v1.GetRecommendationsResponseBiZggithub.com/example/ecommerce-platform/backend/proto-gen/go/ecommerce/recommendation/v1;recommendationv1b\x06proto3"

var (
	file_ecommerce_recommendation_v1_recommendation_proto_rawDescOnce sync.Once
	file_ecommerce_recommendation_v1_recommendation_proto_rawDescData []byte
)

func file_ecommerce_recommendation_v1_recommendation_proto_rawDescGZIP() []byte {
	file_ecommerce_recommendation_v1_recommendation_proto_rawDescOnce.Do(func() {
		file_ecommerce_recommendation_v1_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ecommerce_recommendation_v1_recommendation_proto_rawDesc), len(file_ecommerce_recommendation_v1_recommendation_proto_rawDesc)))
	})
	return file_ecommerce_recommendation_v1_recommendation_proto_rawDescData
}

var file_ecommerce_recommendation_v1_recommendation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ecommerce_recommendation_v1_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ecommerce_recommendation_v1_recommendation_proto_goTypes = []any{
	(RecommendationType)(0),            // 0: ecommerce.recommendation.v1.RecommendationType
	(RecommendationContext)(0),         // 1: ecommerce.recommendation.v1.RecommendationContext
	(*GetRecommendationsRequest)(nil),  // 2: ecommerce.recommendation.v1.GetRecommendationsRequest
	(*RecommendationItem)(nil),         // 3: ecommerce.recommendation.v1.RecommendationItem
	(*GetRecommendationsResponse)(nil), // 4: ecommerce.recommendation.v1.GetRecommendationsResponse
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
}
var file_ecommerce_recommendation_v1_recommendation_proto_depIdxs = []int32{
	1, // 0: ecommerce.recommendation.v1.GetRecommendationsRequest.context:type_name -> ecommerce.recommendation.v1.RecommendationContext
	0, // 1: ecommerce.recommendation.v1.GetRecommendationsRequest.type:type_name -> ecommerce.recommendation.v1.RecommendationType
	0, // 2: ecommerce.recommendation.v1.GetRecommendationsResponse.type:type_name -> ecommerce.recommendation.v1.RecommendationType
	3, // 3: ecommerce.recommendation.v1.GetRecommendationsResponse.items:type_name -> ecommerce.recommendation.v1.RecommendationItem
	5, // 4: ecommerce.recommendation.v1.GetRecommendationsResponse.generated_at:type_name -> google.protobuf.Timestamp
	2, // 5: ecommerce.recommendation.v1.RecommendationService.GetRecommendations:input_type -> ecommerce.recommendation.v1.GetRecommendationsRequest
	4, // 6: ecommerce.recommendation.v1.RecommendationService.GetRecommendations:output_type -> ecommerce.recommendation.v1.GetRecommendationsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ecommerce_recommendation_v1_recommendation_proto_init() }
func file_ecommerce_recommendation_v1_recommendation_proto_init() {
	if File_ecommerce_recommendation_v1_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ecommerce_recommendation_v1_recommendation_proto_rawDesc), len(file_ecommerce_recommendation_v1_recommendation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ecommerce_recommendation_v1_recommendation_proto_goTypes,
		DependencyIndexes: file_ecommerce_recommendation_v1_recommendation_proto_depIdxs,
		EnumInfos:         file_ecommerce_recommendation_v1_recommendation_proto_enumTypes,
		MessageInfos:      file_ecommerce_recommendation_v1_recommendation_proto_msgTypes,
	}.Build()
	File_ecommerce_recommendation_v1_recommendation_proto = out.File
	file_ecommerce_recommendation_v1_recommendation_proto_goTypes = nil
	file_ecommerce_recommendation_v1_recommendation_proto_depIdxs = nil
}
