package domain

import "errors"

var (
	ErrInvalidCart              = errors.New("invalid cart")
	ErrInvalidCartOwner         = errors.New("invalid cart owner")
	ErrInvalidCartStatus        = errors.New("invalid cart status")
	ErrInvalidCartItem          = errors.New("invalid cart item")
	ErrInvalidMoney             = errors.New("invalid money")
	ErrInvalidCartTotals        = errors.New("invalid cart totals")
	ErrDuplicateCartItem        = errors.New("duplicate cart item")
	ErrCartItemLimitReached     = errors.New("cart item limit reached")
	ErrCartItemNotFound         = errors.New("cart item not found")
	ErrCartOwnerMissing         = errors.New("cart owner missing")
	ErrCartNotFound             = errors.New("cart not found")
	ErrCartNotActive            = errors.New("cart is not active")
	ErrCartExpired              = errors.New("cart expired")
	ErrActiveCartExists         = errors.New("active cart already exists")
	ErrCartVersionConflict      = errors.New("cart version conflict")
	ErrCartStoreUnavailable     = errors.New("cart store unavailable")
	ErrCacheUnavailable         = errors.New("cart cache unavailable")
	ErrProductIDRequired        = errors.New("product id is required")
	ErrVariantIDRequired        = errors.New("variant id is required")
	ErrItemIDRequired           = errors.New("item id is required")
	ErrUserIDRequired           = errors.New("user id is required")
	ErrGuestCartIDRequired      = errors.New("guest cart id is required")
	ErrGuestSessionIDRequired   = errors.New("guest session id is required")
	ErrGuestCartAccessDenied    = errors.New("guest cart access denied")
	ErrQuantityTooSmall         = errors.New("quantity is too small")
	ErrQuantityTooLarge         = errors.New("quantity is too large")
	ErrProductNotFound          = errors.New("product not found")
	ErrProductNotSellable       = errors.New("product is not sellable")
	ErrVariantNotFound          = errors.New("variant not found")
	ErrVariantNotSellable       = errors.New("variant is not sellable")
	ErrProductPriceInvalid      = errors.New("product price is invalid")
	ErrInsufficientStock        = errors.New("insufficient stock")
	ErrMixedCurrencyCart        = errors.New("cart contains mixed currencies")
	ErrProductUnavailable       = errors.New("product service unavailable")
	ErrCouponCodeRequired       = errors.New("coupon code is required")
	ErrCouponCodeTooLong        = errors.New("coupon code is too long")
	ErrEmptyCart                = errors.New("cart is empty")
	ErrCartOwnershipMismatch    = errors.New("cart ownership mismatch")
	ErrInvalidCouponPreview     = errors.New("invalid coupon preview")
	ErrCouponCurrencyMismatch   = errors.New("coupon discount currency mismatch")
	ErrCouponDiscountTooLarge   = errors.New("coupon discount exceeds cart subtotal")
	ErrCouponPreviewUnavailable = errors.New("coupon preview unavailable")
)
