apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/edge.yaml
  - namespaces/core.yaml
  - namespaces/data.yaml
  - namespaces/observability.yaml
  - namespaces/jobs.yaml
  - services/api-gateway
  - services/product-service
  - services/session-service
