apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: core
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: ecommerce-platform
type: Opaque
stringData:
  AUTH_MYSQL_DSN: auth_user:change-me@tcp(mysql.data.svc.cluster.local:3306)/auth_db?parseTime=true&multiStatements=true
  AUTH_REDIS_PASSWORD: change-me
  REFRESH_TOKEN_PEPPER: change-me
  OTP_HASH_PEPPER: change-me
  OTP_RATE_LIMIT_PEPPER: change-me
  SESSION_EVENT_PEPPER: change-me
  jwt-private.pem: |
    -----BEGIN PRIVATE KEY-----
    change-me
    -----END PRIVATE KEY-----
  jwt-public.pem: |
    -----BEGIN PUBLIC KEY-----
    change-me
    -----END PUBLIC KEY-----
