apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: core
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
  ports:
    - { name: http, port: 8081, targetPort: http, protocol: TCP }
