apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: core
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: ecommerce-platform
data:
  SERVICE_NAME: product-service
  APP_ENV: dev
  PRODUCT_HTTP_ADDR: :8082
  PRODUCT_MONGO_DATABASE: product_db
  PRODUCT_MONGO_AUTO_CREATE_COLLECTIONS: "false"
  PRODUCT_EVENTS_ENABLED: "true"
  PRODUCT_EVENT_BROKER: kafka
  PRODUCT_EVENTS_TOPIC: product.events
  PRODUCT_OUTBOX_WORKER_ENABLED: "true"
  PRODUCT_KAFKA_BROKERS: kafka.data.svc.cluster.local:9092
  LOG_LEVEL: info
