apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: core
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: ecommerce-platform
type: Opaque
stringData:
  PRODUCT_MONGO_URI: mongodb://product_user:change-me@mongodb.data.svc.cluster.local:27017/product_db
