apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: edge
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: ecommerce-platform
type: Opaque
stringData:
  REDIS_PASSWORD: change-me
  OBSERVABILITY_HASH_SALT: change-me
  PAYMENT_INTERNAL_API_TOKEN: change-me-at-least-32-characters
  SESSION_SERVICE_ADMIN_TOKEN: change-me-at-least-32-characters
