apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: edge
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api-gateway
  ports:
    - { name: http, port: 80, targetPort: http, protocol: TCP }
    - { name: http-internal, port: 8080, targetPort: http, protocol: TCP }
    - { name: grpc, port: 9090, targetPort: grpc, protocol: TCP }
    - { name: metrics, port: 9091, targetPort: metrics, protocol: TCP }
