// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ecommerce/notification/v1/notification.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OTPChannel int32

const (
	OTPChannel_OTP_CHANNEL_UNSPECIFIED OTPChannel = 0
	OTPChannel_OTP_CHANNEL_EMAIL       OTPChannel = 1
	OTPChannel_OTP_CHANNEL_SMS         OTPChannel = 2
)

// Enum value maps for OTPChannel.
var (
	OTPChannel_name = map[int32]string{
		0: "OTP_CHANNEL_UNSPECIFIED",
		1: "OTP_CHANNEL_EMAIL",
		2: "OTP_CHANNEL_SMS",
	}
	OTPChannel_value = map[string]int32{
		"OTP_CHANNEL_UNSPECIFIED": 0,
		"OTP_CHANNEL_EMAIL":       1,
		"OTP_CHANNEL_SMS":         2,
	}
)

func (x OTPChannel) Enum() *OTPChannel {
	p := new(OTPChannel)
	*p = x
	return p
}

func (x OTPChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OTPChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_ecommerce_notification_v1_notification_proto_enumTypes[0].Descriptor()
}

func (OTPChannel) Type() protoreflect.EnumType {
	return &file_ecommerce_notification_v1_notification_proto_enumTypes[0]
}

func (x OTPChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OTPChannel.Descriptor instead.
func (OTPChannel) EnumDescriptor() ([]byte, []int) {
	return file_ecommerce_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

type SendOTPRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId      string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel          OTPChannel             `protobuf:"varint,3,opt,name=channel,proto3,enum=ecommerce.notification.v1.OTPChannel" json:"channel,omitempty"`
	Target           string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Otp              string                 `protobuf:"bytes,5,opt,name=otp,proto3" json:"otp,omitempty"`
	ExpiresInMinutes int32                  `protobuf:"varint,6,opt,name=expires_in_minutes,json=expiresInMinutes,proto3" json:"expires_in_minutes,omitempty"`
	Purpose          string                 `protobuf:"bytes,7,opt,name=purpose,proto3" json:"purpose,omitempty"`
	CorrelationId    string                 `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendOTPRequest) Reset() {
	*x = SendOTPRequest{}
	mi := &file_ecommerce_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOTPRequest) ProtoMessage() {}

func (x *SendOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOTPRequest.ProtoReflect.Descriptor instead.
func (*SendOTPRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendOTPRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *SendOTPRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendOTPRequest) GetChannel() OTPChannel {
	if x != nil {
		return x.Channel
	}
	return OTPChannel_OTP_CHANNEL_UNSPECIFIED
}

func (x *SendOTPRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SendOTPRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *SendOTPRequest) GetExpiresInMinutes() int32 {
	if x != nil {
		return x.ExpiresInMinutes
	}
	return 0
}

func (x *SendOTPRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *SendOTPRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type SendOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOTPResponse) Reset() {
	*x = SendOTPResponse{}
	mi := &file_ecommerce_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOTPResponse) ProtoMessage() {}

func (x *SendOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOTPResponse.ProtoReflect.Descriptor instead.
func (*SendOTPResponse) Descriptor() ([]byte, []int) {
	return file_ecommerce_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendOTPResponse) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *SendOTPResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetNotificationPreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationPreferenceRequest) Reset() {
	*x = GetNotificationPreferenceRequest{}
	mi := &file_ecommerce_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationPreferenceRequest) ProtoMessage() {}

func (x *GetNotificationPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationPreferenceRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

type UpdateNotificationPreferenceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EmailEnabled     *bool                  `protobuf:"varint,1,opt,name=email_enabled,json=emailEnabled,proto3,oneof" json:"email_enabled,omitempty"`
	SmsEnabled       *bool                  `protobuf:"varint,2,opt,name=sms_enabled,json=smsEnabled,proto3,oneof" json:"sms_enabled,omitempty"`
	PushEnabled      *bool                  `protobuf:"varint,3,opt,name=push_enabled,json=pushEnabled,proto3,oneof" json:"push_enabled,omitempty"`
	MarketingEnabled *bool                  `protobuf:"varint,4,opt,name=marketing_enabled,json=marketingEnabled,proto3,oneof" json:"marketing_enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateNotificationPreferenceRequest) Reset() {
	*x = UpdateNotificationPreferenceRequest{}
	mi := &file_ecommerce_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationPreferenceRequest) ProtoMessage() {}

func (x *UpdateNotificationPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationPreferenceRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_ecommerce_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateNotificationPreferenceRequest) GetEmailEnabled() bool {
	if x != nil && x.EmailEnabled != nil {
		return *x.EmailEnabled
	}
	return false
}

func (x *UpdateNotificationPreferenceRequest) GetSmsEnabled() bool {
	if x != nil && x.SmsEnabled != nil {
		return *x.SmsEnabled
	}
	return false
}

func (x *UpdateNotificationPreferenceRequest) GetPushEnabled() bool {
	if x != nil && x.PushEnabled != nil {
		return *x.PushEnabled
	}
	return false
}

func (x *UpdateNotificationPreferenceRequest) GetMarketingEnabled() bool {
	if x != nil && x.MarketingEnabled != nil {
		return *x.MarketingEnabled
	}
	return false
}

type NotificationPreference struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EmailEnabled     bool                   `protobuf:"varint,1,opt,name=email_enabled,json=emailEnabled,proto3" json:"email_enabled,omitempty"`
	SmsEnabled       bool                   `protobuf:"varint,2,opt,name=sms_enabled,json=smsEnabled,proto3" json:"sms_enabled,omitempty"`
	PushEnabled      bool                   `protobuf:"varint,3,opt,name=push_enabled,json=pushEnabled,proto3" json:"push_enabled,omitempty"`
	MarketingEnabled bool                   `protobuf:"varint,4,opt,name=marketing_enabled,json=marketingEnabled,proto3" json:"marketing_enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotificationPreference) Reset() {
	*x = NotificationPreference{}
	mi := &file_ecommerce_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreference) ProtoMessage() {}

func (x *NotificationPreference) ProtoReflect() protoreflect.Message {
	mi := &file_ecommerce_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreference.ProtoReflect.Descriptor instead.
func (*NotificationPreference) Descriptor() ([]byte, []int) {
	return file_ecommerce_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *NotificationPreference) GetEmailEnabled() bool {
	if x != nil {
		return x.EmailEnabled
	}
	return false
}

func (x *NotificationPreference) GetSmsEnabled() bool {
	if x != nil {
		return x.SmsEnabled
	}
	return false
}

func (x *NotificationPreference) GetPushEnabled() bool {
	if x != nil {
		return x.PushEnabled
	}
	return false
}

func (x *NotificationPreference) GetMarketingEnabled() bool {
	if x != nil {
		return x.MarketingEnabled
	}
	return false
}

var File_ecommerce_notification_v1_notification_proto protoreflect.FileDescriptor

const file_ecommerce_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	",ecommerce/notification/v1/notification.proto\x12\x19ecommerce.notification.v1\"\xa6\x02\n" +
	"\x0eSendOTPRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12?\n" +
	"\achannel\x18\x03 \x01(\x0e2%.ecommerce.notification.v1.OTPChannelR\achannel\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x10\n" +
	"\x03otp\x18\x05 \x01(\tR\x03otp\x12,\n" +
	"\x12expires_in_minutes\x18\x06 \x01(\x05R\x10expiresInMinutes\x12\x18\n" +
	"\apurpose\x18\a \x01(\tR\apurpose\x12%\n" +
	"\x0ecorrelation_id\x18\b \x01(\tR\rcorrelationId\"J\n" +
	"\x0fSendOTPResponse\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\"\n" +
	" GetNotificationPreferenceRequest\"\x98\x02\n" +
	"#UpdateNotificationPreferenceRequest\x12(\n" +
	"\remail_enabled\x18\x01 \x01(\bH\x00R\femailEnabled\x88\x01\x01\x12$\n" +
	"\vsms_enabled\x18\x02 \x01(\bH\x01R\n" +
	"smsEnabled\x88\x01\x01\x12&\n" +
	"\fpush_enabled\x18\x03 \x01(\bH\x02R\vpushEnabled\x88\x01\x01\x120\n" +
	"\x11marketing_enabled\x18\x04 \x01(\bH\x03R\x10marketingEnabled\x88\x01\x01B\x10\n" +
	"\x0e_email_enabledB\x0e\n" +
	"\f_sms_enabledB\x0f\n" +
	"\r_push_enabledB\x14\n" +
	"\x12_marketing_enabled\"\xae\x01\n" +
	"\x16NotificationPreference\x12#\n" +
	"\remail_enabled\x18\x01 \x01(\bR\femailEnabled\x12\x1f\n" +
	"\vsms_enabled\x18\x02 \x01(\bR\n" +
	"smsEnabled\x12!\n" +
	"\fpush_enabled\x18\x03 \x01(\bR\vpushEnabled\x12+\n" +
	"\x11marketing_enabled\x18\x04 \x01(\bR\x10marketingEnabled*U\n" +
	"\n" +
	"OTPChannel\x12\x1b\n" +
	"\x17OTP_CHANNEL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11OTP_CHANNEL_EMAIL\x10\x01\x12\x13\n" +
	"\x0fOTP_CHANNEL_SMS\x10\x022\x99\x03\n" +
	"\x13NotificationService\x12`\n" +
	"\aSendOTP\x12).ecommerce.notification.v1.SendOTPRequest\x1a*.ecommerce.notification.v1.SendOTPResponse\x12\x8b\x01\n" +
	"\x19GetNotificationPreference\x12;.ecommerce.notification.v1.GetNotificationPreferenceRequest\x1a1.ecommerce.notification.v1.NotificationPreference\x12\x91\x01\n" +
	"\x1cUpdateNotificationPreference\x12>.ecommerce.notification.v1.UpdateNotificationPreferenceRequest\x1a1.ecommerce.notification.v1.NotificationPreferenceBpZngithub.com/example/ecommerce-platform/backend/services/notification-service/api/notification/v1;notificationv1b\x06proto3"

var (
	file_ecommerce_notification_v1_notification_proto_rawDescOnce sync.Once
	file_ecommerce_notification_v1_notification_proto_rawDescData []byte
)

func file_ecommerce_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_ecommerce_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_ecommerce_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ecommerce_notification_v1_notification_proto_rawDesc), len(file_ecommerce_notification_v1_notification_proto_rawDesc)))
	})
	return file_ecommerce_notification_v1_notification_proto_rawDescData
}

var file_ecommerce_notification_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ecommerce_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ecommerce_notification_v1_notification_proto_goTypes = []any{
	(OTPChannel)(0),                             // 0: ecommerce.notification.v1.OTPChannel
	(*SendOTPRequest)(nil),                      // 1: ecommerce.notification.v1.SendOTPRequest
	(*SendOTPResponse)(nil),                     // 2: ecommerce.notification.v1.SendOTPResponse
	(*GetNotificationPreferenceRequest)(nil),    // 3: ecommerce.notification.v1.GetNotificationPreferenceRequest
	(*UpdateNotificationPreferenceRequest)(nil), // 4: ecommerce.notification.v1.UpdateNotificationPreferenceRequest
	(*NotificationPreference)(nil),              // 5: ecommerce.notification.v1.NotificationPreference
}
var file_ecommerce_notification_v1_notification_proto_depIdxs = []int32{
	0, // 0: ecommerce.notification.v1.SendOTPRequest.channel:type_name -> ecommerce.notification.v1.OTPChannel
	1, // 1: ecommerce.notification.v1.NotificationService.SendOTP:input_type -> ecommerce.notification.v1.SendOTPRequest
	3, // 2: ecommerce.notification.v1.NotificationService.GetNotificationPreference:input_type -> ecommerce.notification.v1.GetNotificationPreferenceRequest
	4, // 3: ecommerce.notification.v1.NotificationService.UpdateNotificationPreference:input_type -> ecommerce.notification.v1.UpdateNotificationPreferenceRequest
	2, // 4: ecommerce.notification.v1.NotificationService.SendOTP:output_type -> ecommerce.notification.v1.SendOTPResponse
	5, // 5: ecommerce.notification.v1.NotificationService.GetNotificationPreference:output_type -> ecommerce.notification.v1.NotificationPreference
	5, // 6: ecommerce.notification.v1.NotificationService.UpdateNotificationPreference:output_type -> ecommerce.notification.v1.NotificationPreference
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ecommerce_notification_v1_notification_proto_init() }
func file_ecommerce_notification_v1_notification_proto_init() {
	if File_ecommerce_notification_v1_notification_proto != nil {
		return
	}
	file_ecommerce_notification_v1_notification_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ecommerce_notification_v1_notification_proto_rawDesc), len(file_ecommerce_notification_v1_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ecommerce_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_ecommerce_notification_v1_notification_proto_depIdxs,
		EnumInfos:         file_ecommerce_notification_v1_notification_proto_enumTypes,
		MessageInfos:      file_ecommerce_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_ecommerce_notification_v1_notification_proto = out.File
	file_ecommerce_notification_v1_notification_proto_goTypes = nil
	file_ecommerce_notification_v1_notification_proto_depIdxs = nil
}
